"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { tasksApi } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { TASK_TYPE_LABELS } from "@/lib/utils";

const TASK_TYPES = ["coding", "reasoning", "comparison", "correction"] as const;

export function TaskForm() {
  const router = useRouter();
  const qc = useQueryClient();

  const [form, setForm] = useState({
    title: "",
    prompt: "",
    context: "",
    task_type: "reasoning" as string,
    priority: 0,
    annotations_required: 1,
  });
  const [error, setError] = useState("");

  const { mutate: create, isPending } = useMutation({
    mutationFn: (data: unknown) => tasksApi.create(data),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["tasks"] });
      router.push("/researcher/tasks");
    },
    onError: (err: Error) => setError(err.message),
  });

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError("");

    create({
      title: form.title,
      prompt: form.prompt,
      context: form.context || null,
      task_type: form.task_type,
      priority: form.priority,
      annotations_required: form.annotations_required,
      metadata: {},
    });
  }

  const set = (k: string, v: unknown) => setForm((f) => ({ ...f, [k]: v }));

  return (
    <form onSubmit={handleSubmit} className="space-y-6 max-w-2xl">
      <Card>
        <CardHeader>
          <CardTitle>Task Details</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="title">Title</Label>
            <Input
              id="title"
              value={form.title}
              onChange={(e) => set("title", e.target.value)}
              placeholder="Brief description of the task"
              required
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="task_type">Task Type</Label>
            <div className="flex gap-2 flex-wrap">
              {TASK_TYPES.map((t) => (
                <button
                  key={t}
                  type="button"
                  onClick={() => set("task_type", t)}
                  className={`px-3 py-1.5 rounded-md text-sm font-medium border transition-colors ${
                    form.task_type === t
                      ? "bg-primary text-primary-foreground border-primary"
                      : "border-border hover:bg-accent"
                  }`}
                >
                  {TASK_TYPE_LABELS[t]}
                </button>
              ))}
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="prompt">Prompt</Label>
            <Textarea
              id="prompt"
              value={form.prompt}
              onChange={(e) => set("prompt", e.target.value)}
              placeholder="The main instruction or question for the annotator"
              className="min-h-[120px]"
              required
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="context">
              Context <span className="text-muted-foreground font-normal">(optional)</span>
            </Label>
            <Textarea
              id="context"
              value={form.context}
              onChange={(e) => set("context", e.target.value)}
              placeholder="Additional background information for the annotator"
              className="min-h-[80px]"
            />
          </div>

          <p className="text-xs text-muted-foreground rounded-md bg-muted/50 px-3 py-2">
            AI responses are auto-generated by Claude when the task is published.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Quality Settings</CardTitle>
        </CardHeader>
        <CardContent className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="annotations_required">Annotations Required</Label>
            <Input
              id="annotations_required"
              type="number"
              min={1}
              max={10}
              value={form.annotations_required}
              onChange={(e) => set("annotations_required", Number(e.target.value))}
            />
            <p className="text-xs text-muted-foreground">Set &gt;1 for inter-annotator agreement</p>
          </div>
          <div className="space-y-2">
            <Label htmlFor="priority">Priority</Label>
            <Input
              id="priority"
              type="number"
              min={0}
              max={100}
              value={form.priority}
              onChange={(e) => set("priority", Number(e.target.value))}
            />
            <p className="text-xs text-muted-foreground">Higher = served first in queue</p>
          </div>
        </CardContent>
      </Card>

      {error && <p className="text-sm text-destructive">{error}</p>}

      <div className="flex gap-3">
        <Button type="submit" disabled={isPending}>
          {isPending ? "Creating…" : "Create Task"}
        </Button>
        <Button type="button" variant="outline" onClick={() => router.back()}>
          Cancel
        </Button>
      </div>
    </form>
  );
}
